name: Recreate Branches from Master

on:
  workflow_dispatch:

jobs:
  recreate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get list of branches to recreate
        id: branches
        run: |
          git fetch origin
          BRANCHES=$(git for-each-ref --format='%(refname:short)' refs/remotes/origin | grep -vE '^(origin/master|origin/HEAD)' | sed 's|origin/||')
          echo "branches=$BRANCHES" >> $GITHUB_OUTPUT

      - name: Recreate each branch from master
        run: |
          for branch in ${{ steps.branches.outputs.branches }}; do
            echo "Recreating branch: $branch"
            git push origin --delete $branch || echo "Branch $branch may not exist remotely"
            git checkout -b $branch origin/master
            git push origin $branch --force
          done
